import BarbacoaJicama from '../../../images/Diets/barbacoa_jicama.jpg';
import TangyBbqChicken from '../../../images/Diets/tangy_bbq_chicken.jpg';
import SpicyChickenVegetableSoup from '../../../images/Diets/spicy_chicken_vegetable_soup.jpg';
import SpinachArtichokeDip from '../../../images/Diets/spinach_artichoke_dip.jpg';
import PumpkinPieShake from '../../../images/Diets/Pumpkin_Pie_Smoothie.jpg';
import ChickenWalnutSalad from '../../../images/Diets/chicken_walnut_salad.jpg';

var data = [
  {
    img: BarbacoaJicama,
    title: 'Super-Easy Barbacoa & Jicama Tacos',
    servings: 6,
    cookTime: 40,
    featured: true,
    category: 'Muscle Gain',
    calories: 456,
    protein: '40g',
    fat: '9g',
    carbs: '32g',
    description: 'Prep these low-carb tacos up to five days in advance for hassle-free eating.',
    ingredients: ["1 tsp fine sea salt",
      "½ tsp ground black pepper",
      "1 tbsp ground cumin",
      "1 tbsp chipotle chili powder",
      "1 tbsp dried Mexican oregano leaves",
      "½ tsp ground cloves",
      "3 lbs chuck roast, cut into 8 large chunks",
      "2 tbsp salted butter",
      "4 garlic cloves, minced",
      "3 bay leaves",
      "¼ cup cider vinegar",
      "¼ cup fresh lime juice (about 2 limes)",
      "1 large jicama, peeled and sliced into thin discs",
      "1 lime, quartered, for garnish",
      "1 large avocado, sliced, for garnish",
      "Chopped fresh cilantro, for garnish"],
    directions: ["In a small bowl, mix together the salt, pepper, cumin, chili powder, oregano, and cloves. Dust the pieces of chuck roast with the spice mixture, making sure to coat all sides well.",
      "Melt the butter in a large frying or sauté pan over high heat. Add the beef in batches so that the pan isn’t overcrowded. Sear the beef for about 3 minutes per side, or until it develops a nice char. Transfer the cooked beef to a slow cooker and repeat with the remaining meat.",
      "Add the garlic and bay leaves to the beef in the slow cooker. Pour in the vinegar and lime juice. Cover, and cook for 4 hours on high, or until the beef falls apart when tested with a fork.",
      "Remove and discard the bay leaves. Then, working in the slow cooker, use two forks to shred the beef. Stir it in the accumulated juices.",
      "To make the jicama tortillas, place the jicama discs in a steamer basket over boiling water and steam for 3 minutes, or place them in a microwave-safe bowl with 2 tbsp water, cover, and microwave on high for 3 minutes. They’re finished when they become flexible. Let cool, then drain over paper towels. Top the jicama with the shredded beef and garnish with lime wedges, avocado, and cilantro."],
  },
  {
    img: PumpkinPieShake,
    title: 'Post-workout Shake: Pumpkin Pie',
    servings: 1,
    cookTime: 1,
    featured: true,
    category: 'Protien Shakes',
    calories: 200,
    protein: '19g',
    fat: '3g',
    carbs: '25g',
    description: 'Spruce up your boring vanilla, or chocolate post-workout protein shake with this pumpkin pie milkshake.',
    ingredients: ["¼ cup unsweetened almond milk",
      "½ cup pumpkin",
      "½ cup organic yogurt",
      "½ cup vanilla whey protein powder",
      "1 tsp pure organic honey",
      "1 tsp graham cracker crumbs",
      "¾ tsp ground cinnamon",
      "½ tsp ground nutmeg",
      "1 tsp sugar-free pumpkin instant Jell-O Pudding Mix"],
    directions: ["Add all of the ingredients into a blender and blend on medium-high for 1 minute or until smooth.",]
  },
  {
    img: ChickenWalnutSalad,
    title: 'Chicken-walnut Salad With Pomegranate Seeds',
    servings: 4,
    cookTime: 40,
    featured: true,
    category: 'Fat Loss',
    calories: 162,
    protein: '14g',
    fat: '9g',
    carbs: '4g',
    description: 'Cooking your chicken in bulk is the smart way to prep your meals for the week',
    ingredients: ["8 oz leftover skinless chicken, chopped",
      "1/2 medium onion, finely chopped",
      "1 1 celery rib, finely chopped",
      "1/4 cup (1 oz) finely chopped walnuts",
      "2 Tbsp pomegranate arils/seeds (or dried cranberries)",
      "2 Tbsp light mayonnaise",
      "2 Tbsp nonfat plain Greek yogurt",
      "1 Tbsp Dijon mustard",
      "1 tsp fresh lemon juice",
      "1/4 tsp salt",
      "1/8 tsp ground black pepper",
      "4 (8-inch) low-carb, whole-wheat flour tortillas"],
    directions: ["In a medium bowl, combine chicken, onion, celery, and walnuts with pomegranate arils.",
      "In a small bowl, whisk together mayo, yogurt, mustard, lemon juice, salt, and black pepper until well-combined. Add to chicken. Stir to coat evenly.",
      "Add chicken salad to tortillas. Fold the sides in; bring bottom up; roll to close."]
  },
  {
    img: SpicyChickenVegetableSoup,
    title: 'Spicy Chicken and Root Vegetabe Soup',
    servings: 4,
    cookTime: 60,
    featured: true,
    category: 'Muscle Gain',
    calories: 273,
    protein: '25g',
    fat: '8g',
    carbs: '32g',
    description: "This soup recipe is the perfect answer to leftover turkey or chicken.",
    ingredients: ["1 cup packed baby spinach",
      "1 tbsp olive oil",
      "1 medium onion, chopped",
      "1 medium carrot, chopped",
      "1 celery rib, chopped",
      "1 medium turnip, chopped",
      "1 (15 oz) can brown lentils, drained",
      "6 oz leftover skinless chicken, shredded",
      "6 cups (48 fluid oz) low-sodium chicken stock",
      "1 tbsp mirin (Japanese sweet rice wine found in the Asian-foods",
      "2 bay leaves",
      "1/8 tsp cayenne"],
    directions: ["Stack spinach leaves, roll, then slice into ribbons.",
      "Heat oil in a large pot over medium heat. When simmering, add onion, carrot, celery, and turnip. Cook until onion is translucent, about 4 minutes. Add lentils, chicken, stock, mirin, and bay leaves; stir to combine. Turn heat up to high and bring to a boil, then reduce heat, cover, and simmer until lentils are tender, about 20 minutes.",
      "Remove bay leaves. Stir in cayenne and spinach. Ladle into bowls."]
  },
  {
    img: TangyBbqChicken,
    title: 'Tangy Barbecue Chicken',
    servings: 4,
    cookTime: 60,
    featured: true,
    category: 'Fat Loss',
    calories: 308,
    protein: '52g',
    fat: '2g',
    carbs: '12g',
    description: "If chicken breast is among your favorite go-tos for a tasty and reliable protein fix, you’ll want to add this dish to your muscle-building arsenal. This version gets its kick from tangy apple cider vinegar and spicy mustard paired with just a little bit of brown sugar and ketchup. ",
    ingredients: ["2/3 cup apple cider vinegar",
      "1/2 cup yellow mustard",
      "1 tsp onion powder",
      "1 tsp garlic powder",
      "2 pinches salt",
      "1/8 cup brown sugar",
      "1/2 cup low-sodium ketchup",
      "4 chicken breasts"],
    directions: ["Preheat grill. Place all ingredients except chicken in a sauce pan. Heat over medium flame, cooking until contents are reduced by 50%.",
      "Spread barbecue sauce on chicken breasts and place on grill. (Sauce can also be cooled for later use.)",
      "Grill breasts 4-5 minutes on each side, or until no longer pink inside."]
  },
  {
    img: SpinachArtichokeDip,
    title: 'Greek Spinach and Artichoke Dip',
    servings: 8,
    cookTime: 15,
    featured: true,
    category: 'Fat Loss',
    calories: 116,
    protein: '7g',
    fat: '7g',
    carbs: '9g',
    description: "Lighten up this spinach-artichoke spread with Greek yogurt and pita chips. It makes for the perfect low-cal yet traditional appetizer you can serve at a party that won’t have people running for the door.",
    ingredients: ["2 tsp olive oil",
      "2 garlic cloves, minced",
      "10 oz frozen spinach, thawed and drained",
      "1 (14 oz) can artichoke hearts, drained and chopped",
      "1 cup plain nonfat Greek yogurt",
      "1 cup reduced-fat cream cheese",
      "½ cup grated Parmesan cheese", "Salt and pepper"],
    directions: ["Heat oil in a large saucepan over medium heat. Add garlic, spinach, and artichokes. Cook until tender, about 5 minutes.",
      "Stir in yogurt and cream cheese. Add Parmesan and salt and pepper to taste. Cook, stirring occasionally, until thickened, 5 to 10 minutes. Serve warm."]
  },
]

export default data;

